inherit_from: .rubocop_todo.yml

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - 'Rakefile'

Style/IfUnlessModifier:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/TrailingComma:
  Enabled: false
